/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ittapiros;



import java.io.IOException;
import java.nio.file.Files;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Nami
 */
public class felulet extends javax.swing.JFrame {

    /**
     * Creates new form felulet
     */
    private int golyo;
    private int hanyPohar;
    private Path fajl=Paths.get("jatek.txt");
    private Path tippFajl=Paths.get("tipp.dep");
    public felulet() {
        initComponents();
         hanyPohar=3;
        elhelyez(hanyPohar);
        if(Files.exists(tippFajl)){
            this.setTitle("A "+golyo+" pohár alatt van a golyó");
        }
       

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        btnPohar1 = new javax.swing.JButton();
        btnPohar2 = new javax.swing.JButton();
        btnPohar3 = new javax.swing.JButton();
        lbTipp = new javax.swing.JLabel();
        ckUjHely = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuMentes = new javax.swing.JMenu();
        mniMentes = new javax.swing.JMenuItem();
        mniBetoltes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        mniUjJatek = new javax.swing.JMenuItem();
        mni3Pohar = new javax.swing.JMenuItem();
        mni4Pohar = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPohar1.setText("pohár");
        btnPohar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPohar1ActionPerformed(evt);
            }
        });

        btnPohar2.setText("pohár");
        btnPohar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPohar2ActionPerformed(evt);
            }
        });

        btnPohar3.setText("pohár");
        btnPohar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPohar3ActionPerformed(evt);
            }
        });

        lbTipp.setText("játékos tippje: ");

        ckUjHely.setText("tippelésenként új helyre kerüljön a golyó");

        jMenu1.setText("Fájl");

        mnuMentes.setText("mentés");
        jMenu1.add(mnuMentes);

        mniMentes.setText("mentés");
        mniMentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniMentesActionPerformed(evt);
            }
        });
        jMenu1.add(mniMentes);

        mniBetoltes.setText("betöltés");
        mniBetoltes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBetoltesActionPerformed(evt);
            }
        });
        jMenu1.add(mniBetoltes);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Játék");

        jMenu4.setText("új játék");
        jMenu2.add(jMenu4);

        mniUjJatek.setText("uj játék");
        mniUjJatek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniUjJatekActionPerformed(evt);
            }
        });
        jMenu2.add(mniUjJatek);

        mni3Pohar.setText("3 pohár");
        mni3Pohar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni3PoharActionPerformed(evt);
            }
        });
        jMenu2.add(mni3Pohar);

        mni4Pohar.setText("4 pohár");
        mni4Pohar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni4PoharActionPerformed(evt);
            }
        });
        jMenu2.add(mni4Pohar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckUjHely)
                    .addComponent(lbTipp)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPohar1)
                        .addGap(41, 41, 41)
                        .addComponent(btnPohar2)
                        .addGap(51, 51, 51)
                        .addComponent(btnPohar3)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPohar1)
                    .addComponent(btnPohar2)
                    .addComponent(btnPohar3))
                .addGap(19, 19, 19)
                .addComponent(ckUjHely)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbTipp)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mni4PoharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni4PoharActionPerformed
        JOptionPane.showMessageDialog(this, "Jelenleg nem elérhető!");
    }//GEN-LAST:event_mni4PoharActionPerformed

    private void btnPohar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPohar1ActionPerformed
        if(golyo==0){
         lbTipp.setText("játékos tippje: talált");
        }else{
            lbTipp.setText("játékos tippje: nem talált");
        }
        if(ckUjHely.isSelected()){
            elhelyez(hanyPohar);
        }
    }//GEN-LAST:event_btnPohar1ActionPerformed

    private void btnPohar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPohar2ActionPerformed
         if(golyo==1){
         lbTipp.setText("játékos tippje: talált");
        }else{
            lbTipp.setText("játékos tippje: nem talált");
        }
         if(ckUjHely.isSelected()){
            elhelyez(hanyPohar);
        }
         
    }//GEN-LAST:event_btnPohar2ActionPerformed

    private void btnPohar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPohar3ActionPerformed
         if(golyo==2){
         lbTipp.setText("játékos tippje: talált");
        }else{
            lbTipp.setText("játékos tippje: nem talált");
        }
         if(ckUjHely.isSelected()){
            elhelyez(hanyPohar);
        }
    }//GEN-LAST:event_btnPohar3ActionPerformed

    private void mni3PoharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni3PoharActionPerformed
        hanyPohar=3;
    }//GEN-LAST:event_mni3PoharActionPerformed

    private void mniUjJatekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniUjJatekActionPerformed
       elhelyez(hanyPohar);
       lbTipp.setText("játékos tippje:");
    }//GEN-LAST:event_mniUjJatekActionPerformed

    private void mniMentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniMentesActionPerformed
        String txt="Golyó helye; poharak száma\n"+golyo+"; "+hanyPohar;
        
        /*Files.write(fajl, );*/
    }//GEN-LAST:event_mniMentesActionPerformed

    private void mniBetoltesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBetoltesActionPerformed
       if(Files.exists(tippFajl)){
            this.setTitle("A "+golyo+" pohár alatt van a golyó");
        }
        List<String> sor;
       ArrayList<Jatek> jatek=new ArrayList<>();
        try {
            sor=Files.readAllLines(fajl);
            for (int i = 1; i < sor.size(); i++) {
            jatek.add(new Jatek(sor.get(i)));
        }
        } catch (IOException ex) {
           ;
        }
        for (int i = 0; i < jatek.size(); i++) {
          golyo=jatek.get(i).getGolyo();
          hanyPohar=jatek.get(i).getHanyPohar();
        }
        
    }//GEN-LAST:event_mniBetoltesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(felulet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(felulet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(felulet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(felulet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new felulet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPohar1;
    private javax.swing.JButton btnPohar2;
    private javax.swing.JButton btnPohar3;
    private javax.swing.JCheckBox ckUjHely;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel lbTipp;
    private javax.swing.JMenuItem mni3Pohar;
    private javax.swing.JMenuItem mni4Pohar;
    private javax.swing.JMenuItem mniBetoltes;
    private javax.swing.JMenuItem mniMentes;
    private javax.swing.JMenuItem mniUjJatek;
    private javax.swing.JMenu mnuMentes;
    // End of variables declaration//GEN-END:variables

    private void elhelyez(int mennyi) {
        Random rand = new Random();
        golyo = rand.nextInt(mennyi);
//        golyo=((int)Math.random()*mennyi+1);
        //System.out.println(golyo);
        
    }
}
